require("plugins.codecompanion")
require("plugins.completions")
require("plugins.formatting")
require("plugins.git")
require("plugins.lint")
require("plugins.lsp")
require("plugins.telescope")
require("plugins.ui")
